# Generated by Django 5.2.16 on 2026-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'EXECUTED'), (2, 'NOT_EXECUTED')], default=2)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('received_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('received_month', models.PositiveSmallIntegerField()),
                ('received_month_day', models.PositiveSmallIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
